"""add default datetime into search log

Revision ID: 41630a5e9554
Revises: cab4cb959b54
Create Date: 2020-04-30 23:03:58.249394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41630a5e9554'
down_revision = 'cab4cb959b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
