"""add default datetime into search log

Revision ID: 95e062bf2102
Revises: 41630a5e9554
Create Date: 2020-04-30 23:10:11.626611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e062bf2102'
down_revision = '41630a5e9554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
