"""add query into search log

Revision ID: cab4cb959b54
Revises: c51d3ea25e58
Create Date: 2020-04-30 22:49:03.920634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab4cb959b54'
down_revision = 'c51d3ea25e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes_search_logs', sa.Column('query', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes_search_logs', 'query')
    # ### end Alembic commands ###
